### ISSUE TITLE
Link in recheck.ignore leads to 404 Not Found

### ISSUE THREAD

**Issue by gitam** [retest/recheck.cli#109]
Link https://retest.github.io/docs/recheck/how-ignore-works-in-recheck/ in the **recheck.ignore** file leads to the content that doesn't give more information. e.g. tried to click on How ignore works - leads to a page not found.

**Comment by diba1013** [comment]
Thank you for reporting issue. This is most likely an issue since we are currently in the process of writing our documentation and changing a few things around.

We will fix this as fast as possible.  However, your existing `recheck.ignore` will not be replaced once we fixed the [link](https://github.com/retest/recheck/blob/master/src/main/resources/default-recheck.ignore).

In the meantime please visit: https://retest.github.io/docs/recheck/how-ignore-works/ and/or adjust this in your `recheck.ignore`.
